# Generated by Django 6.0.5 on 2026-05-09 05:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, choices=[('product', 'Product'), ('service', 'Service'), ('marketing', 'Marketing'), ('operations', 'Operations'), ('partnership', 'Partnership'), ('revenue_stream', 'Revenue Stream')], max_length=100)),
                ('source', models.CharField(choices=[('ai_generated', 'AI Generated'), ('trend_based', 'Trend Based'), ('feedback_derived', 'Feedback Derived'), ('competitor_gap', 'Competitor Gap')], default='ai_generated', max_length=50)),
                ('feasibility_score', models.SmallIntegerField(blank=True, null=True)),
                ('market_fit_score', models.SmallIntegerField(blank=True, null=True)),
                ('effort_score', models.SmallIntegerField(blank=True, null=True)),
                ('roi_score', models.SmallIntegerField(blank=True, null=True)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('time_to_implement', models.CharField(blank=True, max_length=50)),
                ('required_resources', models.JSONField(blank=True, default=list)),
                ('risks', models.JSONField(blank=True, default=list)),
                ('next_steps', models.JSONField(blank=True, default=list)),
                ('is_saved', models.BooleanField(default=False)),
                ('user_rating', models.SmallIntegerField(blank=True, null=True)),
                ('user_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='business.businessprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='analysis.analysissession')),
            ],
            options={
                'db_table': 'ideas',
                'ordering': ['-overall_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdeaValidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('market_size', models.CharField(blank=True, max_length=100)),
                ('target_customer', models.TextField(blank=True)),
                ('problem_severity', models.SmallIntegerField(blank=True, null=True)),
                ('solution_uniqueness', models.SmallIntegerField(blank=True, null=True)),
                ('competition_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('saturated', 'Saturated')], max_length=20)),
                ('monetization_model', models.CharField(blank=True, max_length=100)),
                ('revenue_potential', models.CharField(blank=True, max_length=100)),
                ('go_to_market', models.TextField(blank=True)),
                ('key_risks', models.JSONField(blank=True, default=list)),
                ('validation_summary', models.TextField(blank=True)),
                ('verdict', models.CharField(blank=True, choices=[('strong_yes', 'Strong Yes'), ('yes', 'Yes'), ('maybe', 'Maybe'), ('no', 'No')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validation', to='ideas.idea')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='analysis.analysissession')),
            ],
            options={
                'db_table': 'idea_validations',
            },
        ),
        migrations.AddIndex(
            model_name='idea',
            index=models.Index(fields=['session'], name='idx_ideas_session'),
        ),
        migrations.AddIndex(
            model_name='idea',
            index=models.Index(fields=['-overall_score'], name='idx_ideas_score'),
        ),
        migrations.AddIndex(
            model_name='idea',
            index=models.Index(fields=['category'], name='idx_ideas_category'),
        ),
        migrations.AddIndex(
            model_name='idea',
            index=models.Index(condition=models.Q(('is_saved', True)), fields=['is_saved'], name='idx_ideas_saved'),
        ),
        migrations.AddIndex(
            model_name='ideavalidation',
            index=models.Index(fields=['idea'], name='idx_validations_idea'),
        ),
    ]
