# Generated by Django 6.0.5 on 2026-05-09 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ideavalidation',
            options={'ordering': ['-created_at']},
        ),
    ]
