# Generated by Django 6.0.5 on 2026-05-09 05:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('website', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('market_position', models.CharField(blank=True, choices=[('leader', 'Leader'), ('challenger', 'Challenger'), ('niche', 'Niche'), ('new', 'New')], max_length=100)),
                ('estimated_size', models.CharField(blank=True, choices=[('startup', 'Startup'), ('smb', 'SMB'), ('enterprise', 'Enterprise')], max_length=100)),
                ('threat_level', models.SmallIntegerField(default=3)),
                ('opportunity_gap', models.TextField(blank=True)),
                ('source_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='business.businessprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='analysis.analysissession')),
            ],
            options={
                'db_table': 'competitors',
                'ordering': ['-threat_level', 'name'],
                'indexes': [models.Index(fields=['session'], name='idx_competitors_session')],
            },
        ),
    ]
