# Generated by Django 6.0.5 on 2026-05-09 05:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('trend_type', models.CharField(blank=True, choices=[('technology', 'Technology'), ('consumer_behavior', 'Consumer Behavior'), ('regulation', 'Regulation'), ('market', 'Market'), ('social', 'Social')], max_length=50)),
                ('momentum', models.CharField(choices=[('emerging', 'Emerging'), ('rising', 'Rising'), ('peaking', 'Peaking'), ('declining', 'Declining')], default='rising', max_length=20)),
                ('relevance_score', models.SmallIntegerField(blank=True, null=True)),
                ('opportunity', models.TextField(blank=True)),
                ('threat', models.TextField(blank=True)),
                ('source_urls', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trends', to='business.businessprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trends', to='analysis.analysissession')),
            ],
            options={
                'db_table': 'trends',
                'ordering': ['-relevance_score', '-created_at'],
                'indexes': [models.Index(fields=['session'], name='idx_trends_session'), models.Index(fields=['-relevance_score'], name='idx_trends_relevance')],
            },
        ),
    ]
