# Generated by Django 6.0.5 on 2026-05-09 05:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=30)),
                ('llm_provider', models.CharField(choices=[('anthropic', 'Anthropic'), ('ollama', 'Ollama'), ('mock', 'Mock')], default='anthropic', max_length=30)),
                ('llm_model', models.CharField(default='claude-sonnet-4-20250514', max_length=100)),
                ('total_tokens', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module_status', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'analysis_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LlmLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('anthropic', 'Anthropic'), ('ollama', 'Ollama'), ('mock', 'Mock')], max_length=30)),
                ('model', models.CharField(max_length=100)),
                ('module', models.CharField(choices=[('competitor', 'Competitor'), ('feedback', 'Feedback'), ('ideation', 'Ideation'), ('trends', 'Trends'), ('validation', 'Validation'), ('report', 'Report')], max_length=50)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'llm_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
