# Generated by Django 6.0.5 on 2026-05-09 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='llmlog',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_logs', to='analysis.analysissession'),
        ),
        migrations.AddIndex(
            model_name='analysissession',
            index=models.Index(fields=['business'], name='idx_sessions_business'),
        ),
        migrations.AddIndex(
            model_name='analysissession',
            index=models.Index(fields=['user'], name='idx_sessions_user'),
        ),
        migrations.AddIndex(
            model_name='analysissession',
            index=models.Index(fields=['status'], name='idx_sessions_status'),
        ),
        migrations.AddIndex(
            model_name='llmlog',
            index=models.Index(fields=['session'], name='idx_llm_logs_session'),
        ),
    ]
