# Generated by Django 6.0.5 on 2026-05-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysissession',
            name='llm_provider',
            field=models.CharField(choices=[('anthropic', 'Anthropic'), ('ollama', 'Ollama'), ('gemini', 'Gemini'), ('mock', 'Mock')], default='anthropic', max_length=30),
        ),
        migrations.AlterField(
            model_name='llmlog',
            name='provider',
            field=models.CharField(choices=[('anthropic', 'Anthropic'), ('ollama', 'Ollama'), ('gemini', 'Gemini'), ('mock', 'Mock')], max_length=30),
        ),
    ]
