# Generated by Django 6.0.5 on 2026-05-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_alter_analysissession_llm_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysissession',
            name='llm_model',
            field=models.CharField(default='llama-3.3-70b-versatile', max_length=100),
        ),
        migrations.AlterField(
            model_name='analysissession',
            name='llm_provider',
            field=models.CharField(choices=[('groq', 'Groq'), ('ollama', 'Ollama'), ('gemini', 'Gemini'), ('mock', 'Mock')], default='mock', max_length=30),
        ),
        migrations.AlterField(
            model_name='llmlog',
            name='provider',
            field=models.CharField(choices=[('groq', 'Groq'), ('ollama', 'Ollama'), ('gemini', 'Gemini'), ('mock', 'Mock')], max_length=30),
        ),
    ]
