# Generated by Django 6.0.5 on 2026-05-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_alter_analysissession_llm_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysissession',
            name='llm_model',
            field=models.CharField(default='qwen3:30b-a3b-instruct-2507-q4_K_M', max_length=100),
        ),
        migrations.AlterField(
            model_name='analysissession',
            name='llm_provider',
            field=models.CharField(choices=[('ollama', 'Ollama'), ('gemini', 'Gemini'), ('mock', 'Mock')], default='ollama', max_length=30),
        ),
        migrations.AlterField(
            model_name='llmlog',
            name='provider',
            field=models.CharField(choices=[('ollama', 'Ollama'), ('gemini', 'Gemini'), ('mock', 'Mock')], max_length=30),
        ),
    ]
