# Generated by Django 6.0.5 on 2026-05-09 05:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('target_market', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('stage', models.CharField(choices=[('idea', 'Idea'), ('startup', 'Startup'), ('growth', 'Growth'), ('enterprise', 'Enterprise')], default='idea', max_length=50)),
                ('website_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'business_profiles',
            },
        ),
    ]
