# Generated by Django 6.0.5 on 2026-05-09 05:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_text', models.TextField()),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('google_reviews', 'Google Reviews'), ('reddit', 'Reddit'), ('twitter', 'Twitter'), ('support_tickets', 'Support Tickets')], default='manual', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_submissions', to='business.businessprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_submissions', to='analysis.analysissession')),
            ],
            options={
                'db_table': 'feedback_submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insight_type', models.CharField(choices=[('pain_point', 'Pain Point'), ('feature_request', 'Feature Request'), ('compliment', 'Compliment'), ('bug', 'Bug'), ('question', 'Question')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('frequency_score', models.SmallIntegerField(default=1)),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('example_quotes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='feedback.feedbacksubmission')),
            ],
            options={
                'db_table': 'feedback_insights',
                'ordering': ['-frequency_score', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='feedbacksubmission',
            index=models.Index(fields=['session'], name='idx_feedback_session'),
        ),
        migrations.AddIndex(
            model_name='feedbackinsight',
            index=models.Index(fields=['submission'], name='idx_insights_submission'),
        ),
        migrations.AddIndex(
            model_name='feedbackinsight',
            index=models.Index(fields=['insight_type'], name='idx_insights_type'),
        ),
    ]
