# Generated by Django 6.0.5 on 2026-05-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='ks_audio',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='ks_audio_content_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='report',
            name='ks_audio_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='ks_translation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='report',
            name='localization_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='localization_status',
            field=models.CharField(blank=True, default='pending', max_length=20),
        ),
    ]
